### ISSUE TITLE
Self-check output in offer

### ISSUE THREAD

**Issue by evik42** [golemfactory/ya-runtime-vm#161]
Change how self check is executed so it can report some output that has an effect of the contents of the Offer.

**Acceptance criteria:**
- Self check can output the amount of RAM/nr of Cores it sees and that is the basis of the information in the Offer
- Ensure that WASM runtime still works after this change.

**Additional Information:**
- Overview Information about GPU Support first Iteration: https://github.com/golemfactory/golem-internal/issues/625#issuecomment-1547322228
- 1st iteration of GPU Runtime can have limited support. Such limited support should focus first on GPU setups (hardware + software) available in Golem Factory disposition - a.k.a happy path.

![GPU drawio](https://github.com/golemfactory/ya-runtime-vm/assets/126684244/4ba56a7a-4a24-4be6-b046-4aa828615c25)

**Comment by pwalski** [comment]
I do not understand what this health check is?

Among steps `ya-provider` performs on start are:

1. Running `ya-runtime-vm test` which runs some basic `gvmi` as a check if runtime can run anything  at all (`wasi` runtime does not even have `test` param, so provider looks for printing out `--help` message .. https://github.com/golemfactory/yagna/blob/302baa6088a9e3e1cabc35d3fb3a2147852e10ef/agent/provider/src/execution/registry.rs#L380)

2. Running `ya-runtime offer-template` which produces some system info, mostly about CPU features (note there is no num of cores or RAM):
```
{"constraints":"","properties":{"golem.inf.cpu.brand":"AMD Ryzen 9 6900HS with Radeon Graphics","golem.inf.cpu.capabilities":["sse3","pclmulqdq","ssse3","fma","cmpxchg16b","sse41","sse42","movbe","popcnt","aesni","xsave","osxsave","avx","f16c","rdrand","hypervisor","fpu","vme","de","pse","tsc","msr","pae","mce","cx8","apic","sep","mtrr","pge","mca","cmov","pat","pse36","clfsh","mmx","fxsr","sse","sse2","htt","fsgsbase","bmi1","avx2","smep","bmi2","rep_movsb_stosb","invpcid","rdseed","adx","smap","clflushopt","sha","clwb","umip","rdpid"],"golem.inf.cpu.model":"Stepping 1 Family 35 Model 132","golem.inf.cpu.vendor":"AuthenticAMD","golem.runtime.capabilities":["inet","vpn","manifest-support","start-entrypoint"]}}
```
(again, no such cmd in `wasi` runtime so that would be it regarding my breaking support concerns).

3. Finally `ya-provider` prepares `offer` for exising `presets` using data produced by above `offer-template` cmd and system info like num CPUs, RAM, and storage which `ya-provider` generates by itself (instead of using `vm` runtime):
https://github.com/golemfactory/yagna/blob/302baa6088a9e3e1cabc35d3fb3a2147852e10ef/agent/provider/src/hardware.rs#L123

Is this `health check` task even necessary?
Would it not be enough to just extend `vm` runtime `offer-template` cmd output with GPU info while working on https://github.com/golemfactory/ya-runtime-vm/issues/157 ?
