### ISSUE TITLE
Consider: handle docker entrypoints in VM runtime

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/ya-runtime-vm#93]
Why:
- developers wants entrypoint support

What:
- check why it was not supported initially (ask @prekucki or consider old notes)
- estimate effort needed to add the support

**Comment by mfranciszkiewicz** [comment]
Entrypoints were not supported at first due to a narrowed down feature scope of initial releases. Entrypoint handling is implemented in the `init` process, although entrypoints are never executed and the code was not tested.

We need to extend runtime's capability list in order to make providers / runtimes with entrypoint support discoverable on the market, while remaining backward-compatible.

Estimation:
- 2 workdays (incl. testing)
